using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HomeServicesPortal.Migrations
{
    /// <inheritdoc />
    public partial class AddServiceTitleBasePrice : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // NOTE: This migration was auto-generated by diffing the EF model against the last
            // recorded migration, but several of those model differences (Providers.City,
            // Clients.City/Comments/CustomerAlert/Location, the AdminNotifications and
            // Configurations tables, and the CustomerServiceRequests.Status default already being
            // "Initiated") were previously applied directly to the live database out-of-band, not
            // through an EF migration. Those statements are intentionally omitted below — only
            // ServiceTitles.BasePrice is a genuinely new schema change here. The other objects
            // remain correctly represented in the model snapshot so future `dotnet ef migrations
            // add` diffs stay accurate.
            migrationBuilder.AddColumn<decimal>(
                name: "BasePrice",
                table: "ServiceTitles",
                type: "decimal(12,2)",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "BasePrice",
                table: "ServiceTitles");
        }
    }
}
